/*
 * Copyright (c) 2007 through 2026 David Berkman
 *
 * This file is part of the SmallMind Code Project.
 *
 * The SmallMind Code Project is free software, you can redistribute
 * it and/or modify it under either, at your discretion...
 *
 * 1) The terms of GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * ...or...
 *
 * 2) The terms of the Apache License, Version 2.0.
 *
 * The SmallMind Code Project is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License or Apache License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * and the Apache License along with the SmallMind Code Project. If not, see
 * <http://www.gnu.org/licenses/> or <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Additional permission under the GNU Affero GPL version 3 section 7
 * ------------------------------------------------------------------
 * If you modify this Program, or any covered work, by linking or
 * combining it with other code, such other code is not for that reason
 * alone subject to any of the requirements of the GNU Affero GPL
 * version 3.
 */
package org.smallmind.persistence.orm.querydsl.jpa;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import jakarta.persistence.Access;
import jakarta.persistence.AccessType;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.PersistenceUnitTransactionType;
import com.querydsl.core.types.dsl.PathBuilder;
import com.querydsl.jpa.impl.JPADeleteClause;
import com.querydsl.jpa.impl.JPAQuery;
import com.querydsl.jpa.impl.JPAUpdateClause;
import org.hibernate.jpa.HibernatePersistenceProvider;
import org.smallmind.persistence.orm.jpa.JPADurable;
import org.smallmind.persistence.orm.jpa.JPAProxySession;
import org.smallmind.persistence.orm.jpa.JPAProxyTransaction;
import org.smallmind.persistence.orm.spring.jpa.RealizedPersistenceUnitInfo;
import org.smallmind.persistence.sql.DriverManagerDataSource;
import org.smallmind.persistence.sql.testbench.DataSourceAvailableTestCondition;
import org.smallmind.testbench.condition.TestConditions;
import org.smallmind.testbench.docker.DockerApplication;
import org.smallmind.testbench.groundwater.AbstractGroundwaterTest;
import org.springframework.orm.jpa.persistenceunit.MutablePersistenceUnitInfo;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * Integration test for {@link QJPADao} against a real MySQL container started through the docker testbench. It drives
 * the QueryDSL-backed DAO end to end over a genuine Hibernate {@link EntityManager}, covering native CRUD, the
 * id-based {@code list}/{@code scroll} surface, the {@code size}/{@code countByQuery} aggregates, the
 * {@code findByQuery}/{@code listByQuery}/{@code scrollByQuery} read path (both managed-type and explicit
 * return-type overloads), and the {@code updateWithQuery}/{@code deleteWithQuery} bulk-mutation path built from
 * QueryDSL {@link JPAQuery}, {@link JPAUpdateClause}, and {@link JPADeleteClause} clauses.
 *
 * <p>The managed entity extends {@link JPADurable}, so ids are generated by the database on insert; tests capture
 * the generated ids before exercising id-bounded queries. The session is built with {@code boundaryEnforced = false}
 * so the DAO can be driven directly. Writes and bulk statements flush through the entity manager and so are wrapped
 * in an explicit {@link JPAProxyTransaction}; their effects are verified through a fresh entity manager so the
 * DAO session's first-level cache cannot mask a missing database change. Each test starts from an empty table.
 *
 * <p>Requires a running Docker daemon; the {@code mysql:latest} image is pulled on first run.
 */
@Test(groups = "integration")
public class QJPADaoIntegrationTest extends AbstractGroundwaterTest {

  private static final String DRIVER_CLASS_NAME = "com.mysql.cj.jdbc.Driver";
  private static final String JDBC_URL = "jdbc:mysql://localhost:3306/groundwater?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED";
  private static final String USER_NAME = "root";
  private static final String PASSWORD = "secret";

  private EntityManagerFactory entityManagerFactory;

  public QJPADaoIntegrationTest () {

    super(DockerApplication.MYSQL);
  }

  @BeforeClass
  @Override
  public void beforeClass ()
    throws Exception {

    super.beforeClass();

    TestConditions.serial(120, new DataSourceAvailableTestCondition(DRIVER_CLASS_NAME, JDBC_URL, USER_NAME, PASSWORD));

    DriverManagerDataSource dataSource = new DriverManagerDataSource(DRIVER_CLASS_NAME, JDBC_URL, USER_NAME, PASSWORD);
    MutablePersistenceUnitInfo persistenceUnitInfo = new MutablePersistenceUnitInfo();

    persistenceUnitInfo.setPersistenceUnitName("qjpa-dao-it");
    persistenceUnitInfo.setTransactionType(PersistenceUnitTransactionType.RESOURCE_LOCAL);
    persistenceUnitInfo.setNonJtaDataSource(dataSource);
    persistenceUnitInfo.addManagedClassName(Cog.class.getName());
    persistenceUnitInfo.setExcludeUnlistedClasses(true);
    persistenceUnitInfo.getProperties().setProperty("hibernate.dialect", "org.hibernate.dialect.MySQLDialect");
    persistenceUnitInfo.getProperties().setProperty("hibernate.hbm2ddl.auto", "create-drop");

    entityManagerFactory = new HibernatePersistenceProvider().createContainerEntityManagerFactory(new RealizedPersistenceUnitInfo(persistenceUnitInfo), new HashMap<>());
  }

  @AfterClass
  @Override
  public void afterClass ()
    throws Exception {

    try {
      if (entityManagerFactory != null) {
        entityManagerFactory.close();
      }
    } finally {
      super.afterClass();
    }
  }

  @BeforeMethod
  public void clearTable () {

    EntityManager entityManager = entityManagerFactory.createEntityManager();

    try {
      entityManager.getTransaction().begin();
      entityManager.createQuery("delete from Cog").executeUpdate();
      entityManager.getTransaction().commit();
    } finally {
      entityManager.close();
    }
  }

  private JPAProxySession session () {

    return new JPAProxySession("mysql", null, entityManagerFactory, false, false);
  }

  private List<Cog> persistInTransaction (JPAProxySession session, CogDao dao, Cog... cogs) {

    JPAProxyTransaction transaction = session.beginTransaction();
    List<Cog> persisted = new ArrayList<>();

    for (Cog cog : cogs) {
      persisted.add(dao.persist(cog));
    }

    transaction.commit();

    return persisted;
  }

  private Cog findCog (long id) {

    EntityManager entityManager = entityManagerFactory.createEntityManager();

    try {

      return entityManager.find(Cog.class, id);
    } finally {
      entityManager.close();
    }
  }

  public void testPersistAssignsGeneratedIdAndGetRoundTrips () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      Cog persisted = persistInTransaction(session, dao, new Cog("alpha", 5)).get(0);

      Assert.assertNotNull(persisted.getId(), "the database should have generated an id on insert");
      Assert.assertEquals(dao.get(persisted.getId()).getName(), "alpha", "a persisted durable should be retrievable by its generated id");
    } finally {
      session.close();
    }
  }

  public void testAcquireReadsDirectlyFromTheEntityManager () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      Cog persisted = persistInTransaction(session, dao, new Cog("beta", 7)).get(0);

      Cog acquired = dao.acquire(Cog.class, persisted.getId());

      Assert.assertNotNull(acquired, "acquire should load the durable straight from the entity manager");
      Assert.assertEquals(acquired.getName(), "beta");
    } finally {
      session.close();
    }
  }

  public void testDeleteRemovesDurable () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      Cog persisted = persistInTransaction(session, dao, new Cog("doomed", 1)).get(0);

      JPAProxyTransaction transaction = session.beginTransaction();

      dao.delete(persisted);
      transaction.commit();

      Assert.assertNull(findCog(persisted.getId()), "a deleted durable should no longer be present");
    } finally {
      session.close();
    }
  }

  public void testListAndSizeCoverEveryDurable () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      persistInTransaction(session, dao, new Cog("a", 1), new Cog("b", 2), new Cog("c", 3));

      Assert.assertEquals(dao.list().size(), 3);
      Assert.assertEquals(dao.size(), 3L, "size should count every persisted durable");
      Assert.assertEquals(dao.list(2).size(), 2, "the fetch-size bound should cap the result count");
    } finally {
      session.close();
    }
  }

  public void testListGreaterThanReturnsHigherIds () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      List<Cog> persisted = persistInTransaction(session, dao, new Cog("a", 1), new Cog("b", 2), new Cog("c", 3));
      Long lowestId = persisted.get(0).getId();

      List<Cog> higher = dao.list(lowestId, 10);

      Assert.assertEquals(higher.size(), 2, "only ids strictly greater than the lower bound should be returned");
      for (Cog cog : higher) {
        Assert.assertTrue(cog.getId() > lowestId, "every returned id should exceed the lower bound");
      }
    } finally {
      session.close();
    }
  }

  public void testListByIdCollectionReturnsRequestedSubset () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      List<Cog> persisted = persistInTransaction(session, dao, new Cog("a", 1), new Cog("b", 2), new Cog("c", 3));
      Long firstId = persisted.get(0).getId();
      Long lastId = persisted.get(2).getId();

      List<Cog> subset = dao.list(List.of(firstId, lastId));

      Assert.assertEquals(subset.size(), 2, "only the requested ids should be returned");
    } finally {
      session.close();
    }
  }

  public void testScrollVariantsStreamEveryDurable () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      List<Cog> persisted = persistInTransaction(session, dao, new Cog("a", 1), new Cog("b", 2), new Cog("c", 3));

      Assert.assertEquals(drain(dao.scroll()), 3, "scroll should stream every durable");
      // QJPADao.scroll(fetchSize) applies fetchSize as a result cap (limit), unlike ThrongDao's batch-size hint.
      Assert.assertEquals(drain(dao.scroll(2)), 2, "scroll(fetchSize) should cap the streamed result count");
      Assert.assertEquals(drain(dao.scrollById(persisted.get(0).getId(), 10)), 2, "scrollById should stream only ids beyond the lower bound");
    } finally {
      session.close();
    }
  }

  public void testCountByQueryCountsMatchingRows () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      persistInTransaction(session, dao, new Cog("a", 1), new Cog("b", 8), new Cog("c", 9));

      long count = dao.countByQuery(new JPAQueryDetails<Cog>() {

        @Override
        public JPAQuery<Cog> completeQuery (JPAQuery<Cog> query) {

          PathBuilder<Cog> entity = new PathBuilder<>(Cog.class, "entity");

          return query.from(entity).where(entity.getNumber("quantity", Integer.class).goe(5));
        }
      });

      Assert.assertEquals(count, 2L, "only rows at or above the quantity floor should be counted");
    } finally {
      session.close();
    }
  }

  public void testFindByQueryReturnsSingleManagedDurable () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      persistInTransaction(session, dao, new Cog("alpha", 5), new Cog("beta", 9));

      Cog found = dao.findByQuery(new JPAQueryDetails<Cog>() {

        @Override
        public JPAQuery<Cog> completeQuery (JPAQuery<Cog> query) {

          PathBuilder<Cog> entity = new PathBuilder<>(Cog.class, "entity");

          return query.from(entity).where(entity.getString("name").eq("beta"));
        }
      });

      Assert.assertNotNull(found, "the single matching durable should be returned");
      Assert.assertEquals(found.getQuantity(), Integer.valueOf(9));
    } finally {
      session.close();
    }
  }

  public void testFindByQueryWithReturnTypeProjectsScalar () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      Cog persisted = persistInTransaction(session, dao, new Cog("alpha", 5)).get(0);

      String name = dao.findByQuery(String.class, new JPAQueryDetails<String>() {

        @Override
        public JPAQuery<String> completeQuery (JPAQuery<String> query) {

          PathBuilder<Cog> entity = new PathBuilder<>(Cog.class, "entity");

          return query.select(entity.getString("name")).from(entity).where(entity.getNumber("id", Long.class).eq(persisted.getId()));
        }
      });

      Assert.assertEquals(name, "alpha", "the projected scalar column should be returned as the requested type");
    } finally {
      session.close();
    }
  }

  public void testListByQueryReturnsManagedDurables () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      persistInTransaction(session, dao, new Cog("a", 1), new Cog("b", 8), new Cog("c", 9));

      List<Cog> cogs = dao.listByQuery(new JPAQueryDetails<Cog>() {

        @Override
        public JPAQuery<Cog> completeQuery (JPAQuery<Cog> query) {

          PathBuilder<Cog> entity = new PathBuilder<>(Cog.class, "entity");

          return query.from(entity).where(entity.getNumber("quantity", Integer.class).goe(5)).orderBy(entity.getNumber("id", Long.class).asc());
        }
      });

      Assert.assertEquals(cogs.size(), 2, "only rows at or above the quantity floor should be listed");
      Assert.assertEquals(cogs.get(0).getName(), "b");
      Assert.assertEquals(cogs.get(1).getName(), "c");
    } finally {
      session.close();
    }
  }

  public void testListByQueryWithReturnTypeProjectsScalars () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      persistInTransaction(session, dao, new Cog("a", 1), new Cog("b", 2));

      List<String> names = dao.listByQuery(String.class, new JPAQueryDetails<String>() {

        @Override
        public JPAQuery<String> completeQuery (JPAQuery<String> query) {

          PathBuilder<Cog> entity = new PathBuilder<>(Cog.class, "entity");

          return query.select(entity.getString("name")).from(entity).orderBy(entity.getNumber("id", Long.class).asc());
        }
      });

      Assert.assertEquals(names, List.of("a", "b"), "scalar projections should be listed in query order");
    } finally {
      session.close();
    }
  }

  public void testScrollByQueryStreamsMatchingDurables () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      persistInTransaction(session, dao, new Cog("a", 1), new Cog("b", 8), new Cog("c", 9));

      Iterable<Cog> scrolled = dao.scrollByQuery(new JPAQueryDetails<Cog>() {

        @Override
        public JPAQuery<Cog> completeQuery (JPAQuery<Cog> query) {

          PathBuilder<Cog> entity = new PathBuilder<>(Cog.class, "entity");

          return query.from(entity).where(entity.getNumber("quantity", Integer.class).goe(5));
        }
      });

      Assert.assertEquals(drain(scrolled), 2, "scrollByQuery should stream only matching durables");
    } finally {
      session.close();
    }
  }

  public void testUpdateWithQueryRunsBulkUpdate () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      Cog persisted = persistInTransaction(session, dao, new Cog("before", 5)).get(0);
      final Long targetId = persisted.getId();

      JPAProxyTransaction transaction = session.beginTransaction();
      Long affected = dao.updateWithQuery(new JPAUpdateDetails<Cog>(new PathBuilder<>(Cog.class, "entity")) {

        @Override
        public JPAUpdateClause completeUpdate (JPAUpdateClause update) {

          PathBuilder<Cog> entity = new PathBuilder<>(Cog.class, "entity");

          return update.set(entity.getString("name"), "after").where(entity.getNumber("id", Long.class).eq(targetId));
        }
      });

      transaction.commit();

      Assert.assertEquals(affected, Long.valueOf(1L), "the bulk update should report a single affected row");
      Assert.assertEquals(findCog(targetId).getName(), "after", "the bulk update should be visible to a fresh entity manager");
    } finally {
      session.close();
    }
  }

  public void testDeleteWithQueryRunsBulkDelete () {

    JPAProxySession session = session();

    try {

      CogDao dao = new CogDao(session);

      List<Cog> persisted = persistInTransaction(session, dao, new Cog("doomed", 1), new Cog("spared", 2));
      final Long doomedId = persisted.get(0).getId();
      Long sparedId = persisted.get(1).getId();

      JPAProxyTransaction transaction = session.beginTransaction();
      Long affected = dao.deleteWithQuery(new JPADeleteDetails<Cog>(new PathBuilder<>(Cog.class, "entity")) {

        @Override
        public JPADeleteClause completeDelete (JPADeleteClause delete) {

          PathBuilder<Cog> entity = new PathBuilder<>(Cog.class, "entity");

          return delete.where(entity.getNumber("id", Long.class).eq(doomedId));
        }
      });

      transaction.commit();

      Assert.assertEquals(affected, Long.valueOf(1L), "the bulk delete should report a single affected row");
      Assert.assertNull(findCog(doomedId), "the targeted durable should be gone");
      Assert.assertNotNull(findCog(sparedId), "the untargeted durable should survive");
    } finally {
      session.close();
    }
  }

  private int drain (Iterable<Cog> iterable) {

    int count = 0;

    for (Cog ignored : iterable) {
      count++;
    }

    return count;
  }

  @Entity(name = "Cog")
  @Access(AccessType.PROPERTY)
  public static class Cog extends JPADurable<Long, Cog> {

    private static final long serialVersionUID = 1L;

    private String name;
    private Integer quantity;

    public Cog () {

    }

    public Cog (String name, Integer quantity) {

      this.name = name;
      this.quantity = quantity;
    }

    public String getName () {

      return name;
    }

    public void setName (String name) {

      this.name = name;
    }

    public Integer getQuantity () {

      return quantity;
    }

    public void setQuantity (Integer quantity) {

      this.quantity = quantity;
    }
  }

  private static class CogDao extends QJPADao<Long, Cog> {

    private CogDao (JPAProxySession proxySession) {

      super(proxySession);
    }
  }
}
