/*
 * Copyright (c) 2007 through 2026 David Berkman
 *
 * This file is part of the SmallMind Code Project.
 *
 * The SmallMind Code Project is free software, you can redistribute
 * it and/or modify it under either, at your discretion...
 *
 * 1) The terms of GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * ...or...
 *
 * 2) The terms of the Apache License, Version 2.0.
 *
 * The SmallMind Code Project is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License or Apache License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * and the Apache License along with the SmallMind Code Project. If not, see
 * <http://www.gnu.org/licenses/> or <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Additional permission under the GNU Affero GPL version 3 section 7
 * ------------------------------------------------------------------
 * If you modify this Program, or any covered work, by linking or
 * combining it with other code, such other code is not for that reason
 * alone subject to any of the requirements of the GNU Affero GPL
 * version 3.
 */
package org.smallmind.scribe.pen.spring;

import java.util.HashMap;
import org.smallmind.nutsnbolts.spring.SpringPropertyAccessor;
import org.smallmind.nutsnbolts.spring.SpringPropertyAccessorManager;
import org.smallmind.scribe.pen.Appender;
import org.smallmind.scribe.pen.ClassNameTemplate;
import org.smallmind.scribe.pen.Enhancer;
import org.smallmind.scribe.pen.Filter;
import org.smallmind.scribe.pen.Level;
import org.smallmind.scribe.pen.LoggerException;
import org.springframework.beans.factory.InitializingBean;

/**
 * Spring {@link InitializingBean} that reads {@code log.pattern.<key>} and {@code log.level.<key>} Spring
 * properties at startup, then creates and registers a {@link ClassNameTemplate} for each discovered key,
 * applying a shared set of filters, appenders, enhancers, and the auto-fill-context flag to every template.
 */
public class DynamicClassNameTemplateInitializingBean implements InitializingBean {

  private Filter[] filters = new Filter[0];
  private Appender[] appenders = new Appender[0];
  private Enhancer[] enhancers = new Enhancer[0];
  private boolean autoFillLoggerContext = false;

  /**
   * Sets the array of filters that will be applied to every {@link ClassNameTemplate} generated by this bean.
   *
   * @param filters the filters to attach to each generated template
   */
  public void setFilters (Filter[] filters) {

    this.filters = filters;
  }

  /**
   * Sets the array of appenders that will be attached to every {@link ClassNameTemplate} generated by this bean.
   *
   * @param appenders the appenders to attach to each generated template
   */
  public void setAppenders (Appender[] appenders) {

    this.appenders = appenders;
  }

  /**
   * Sets the array of enhancers that will be attached to every {@link ClassNameTemplate} generated by this bean.
   *
   * @param enhancers the enhancers to attach to each generated template
   */
  public void setEnhancers (Enhancer[] enhancers) {

    this.enhancers = enhancers;
  }

  /**
   * Controls whether every generated {@link ClassNameTemplate} will instruct its loggers to auto-capture
   * caller context (class name, method, and line number) for each record.
   *
   * @param autoFillLoggerContext {@code true} to enable automatic context capture; {@code false} to disable it
   */
  public void setAutoFillLoggerContext (boolean autoFillLoggerContext) {

    this.autoFillLoggerContext = autoFillLoggerContext;
  }

  /**
   * Scans all Spring properties for {@code log.pattern.*} and {@code log.level.*} keys, pairs them by shared
   * suffix, and for each pair creates and registers a {@link ClassNameTemplate} configured with the shared
   * filters, appenders, enhancers, auto-fill flag, the parsed {@link Level}, and the class-name pattern.
   *
   * @throws LoggerException if a {@code log.pattern} key has no corresponding {@code log.level} entry
   * @throws Exception       if the Spring property accessor or template registration encounters an error
   */
  @Override
  public void afterPropertiesSet ()
    throws Exception {

    HashMap<String, String> templateMap = new HashMap<>();
    HashMap<String, String> levelMap = new HashMap<>();

    SpringPropertyAccessor springPropertyAccessor = SpringPropertyAccessorManager.getSpringPropertyAccessor();

    for (String propertyKey : springPropertyAccessor.getKeySet()) {
      if (propertyKey.startsWith("log.pattern.")) {
        templateMap.put(propertyKey.substring("log.pattern.".length()), springPropertyAccessor.asString(propertyKey));
      }
      if (propertyKey.startsWith("log.level.")) {
        levelMap.put(propertyKey.substring("log.level.".length()), springPropertyAccessor.asString(propertyKey));
      }
    }

    for (String logKey : templateMap.keySet()) {

      ClassNameTemplate classNameTemplate;
      String levelValue;

      if ((levelValue = levelMap.get(logKey)) == null) {
        throw new LoggerException("Undefined level for log key(%s)", logKey);
      }

      classNameTemplate = new ClassNameTemplate(filters, appenders, enhancers, Level.valueOf(levelValue), autoFillLoggerContext, templateMap.get(logKey));
      classNameTemplate.register();
    }
  }
}
