= Smallmind
:doctype: book
:toc: left
:icons: font
A journey through glue code

[preface]
The SmallMind project is about all the pieces of functionality you need to take care of after you've written your business logic. It's about logging, pooling, monitoring, caching and remoting. It's about doing all this without assumptions or privilege, so that every piece can be dropped, adapted, or extended. This project is opinionated, but we hope those opinions come out of a thoughtful and positive place.

== About

This is a work in progress, which is to say it's mostly code. We're open to opinions, modifications, questions, and, above all, help, because if there's any point to this project, it's to be helpful.

=== Download

All Smallmind modules are pushed to Maven Central under the *org.smallmind* group id. All artifacts which are intended to work together have the same sem version. Explicit module listings can be found in the various sections of this document covering those modules. Wherever possible, dependencies of this project are marked as `<optional>true</optional>`. This does require projects using these libraries to include such dependencies along with the relevant Smallmind modules, but keeps this project from making unwanted decisions. If we've missed any such opportunities, please let us know.

=== Configuration

There is none. IOC projects provide both the base container and configuration. Smallmind provides some occasionally helpful Spring beans, but there's no magic in them. Whatever flavor of dependency injection you prefer should work just as well.

=== Modules

* <<claxon>> - A unified monitoring framework with extensible meters and pluggable metric warehousing integrations (comes with Datadog, JMX, Logging and Prometheus).
* <<spark>> - Maven packaging formats for the construction of self-contained executable build artifacts.

[[claxon,Claxon]]
= Claxon

[partintro]
Claxon is a unified code instrumentation and metric gathering framework that abstracts away the underlying metric warehousing systems, allowing new systems to be plugged in and replaced as needed. It can be safely used as a dependency in libraries to provide instrumentation in a warehouse agnostic fashion, without forcing any particular notion of the underlying metrics storage system on the library adopter. New meters can be created without reference to the eventual warehousing system, and new warehouses can be integrated and used with all Claxon meters.

== Install

To use Claxon you need the `claxon-registry` dependency, and you may add dependencies for any emitters you're interested in the various `claxon-emitter-*` modules. There's also a simple Http endpoint for scraping pull-based emitters in the `claxon-http` module.

.Claxon Registry
[source,xml]
----
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>claxon-registry</artifactId>
  <version>LATEST</version>
</dependency>
----

.Claxon Push-based Integrations
[source,xml]
----
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>claxon-emitter-datadog</artifactId>
  <version>LATEST</version>
</dependency>
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>claxon-emitter-jmx</artifactId>
  <version>LATEST</version>
</dependency>
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>claxon-emitter-logging</artifactId>
  <version>LATEST</version>
</dependency>
----

[[claxon-maven-pull-based, Pull-based Integrations]]
.Claxon Pull-based Integrations
[source,xml]
----
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>claxon-emitter-prometheus</artifactId>
  <version>LATEST</version>
</dependency>
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>claxon-http</artifactId>
  <version>LATEST</version>
</dependency>
----

== Acknowledgments

Thanks to Dropwizard Metrics, micrometer.io and HdrHistogram.

== Design Choices

Metric warehousing systems such as StatsD, InfluxDB or Prometheus all store and provide for the querying of time series data. Some systems allow for the calculation of aggregations (minimums, maximums, velocity, histograms, etc.) upon storing data points, or as part of the provided query capabilities, while others do not. Some systems we may want to integrate with, such as JMX, have no notion of a time series at all. A project such as this one might fulfill its goals by fixing its notion of the meters it allows, and then pushing the responsibility of implementing each of those meters onto the warehouse integrations. This would allow integrations with systems with a built-in notion of aggregations to take advantage of those capabilities. We have instead chosen to ignore most of the differences between warehousing systems, and separate the implementation of meters from the underlying capabilities of the various data stores. That doesn't mean that you can't choose to build your own meters and warehousing integrations that are more tightly coupled, it just means that the meters provided by this project all aggregate on the client, and are uniformly usable on both the provided warehouse integrations, or with new integrations you may choose to create. It means that this framework does not privilege its provided meters in any way, and all of its capabilities, including AOP instrumentation annotations, are extended to any meters you choose to create. Further, you can create new warehouse integrations without having to provide implementations for any meters at all, and those integrations will be usable with all meters which fulfill the contracts for this project.

== Registry

The ClaxonRegistry holds both meters (`org.smallmind.claxon.registry.meter.Meter`) and warehouse integration bindings (`org.smallmind.claxon.registry.Emitter`). Meters should be obtained through the ClaxonRegistry, which accepts the MeterBuilder interface (org.smallmind.claxon.registry.meter.MeterBuilder) through its `register()` method, as opposed to meter implementations directly. MeterBuilder is intended to take only the necessary parameters for constructing instances of Meter, and to be itself lightweight, so that the cost of not building a meter (if already present in the registry) is negligible. If the construction of a meter can't be directly trivialized, this project provides a lazy indirection (`org.smallmind.claxon.registry.meter.LazyBuilder`) which can delay the use of a MeterBuilder until the point of necessity. On the back side, implementations of Emitter are bound by name through the registry's `bind()` method, and called with all aggregated metrics on the configured collection interval. Let's take a closer look at the useful bits...

=== Bind

[small]#`ClaxonRegistry bind(String name, Emitter emitter)`#

Installs and binds an emitter to the specified name, which will then start receiving updates. Reusing a name will rebind that name to the new emitter.

[[claxon-registry-register, Register]]
=== Register

[small]#`<M extends Meter> M register(Class<?> caller, MeterBuilder<M> builder, Tag... tags)`#

Creates and registers a meter if it's not already registered, otherwise returns the currently registered meter. A meter's uniqueness is a combination of the caller's class and the tags passed as parameters to this method. Although the calling class is intended to be the direct caller of this method, that's not a requirement. Think of it the same way many logging systems use a class as the log name, which is intended, but not required to be the class doing the logging. In a similar fashion, whether this meter actually outputs any metrics, and the namespace of those metrics (as passed to this registries bound emitters), will depend upon the class of the caller (see <<claxon-configuration>>). Every possible Meter should have a MeterBuilder available. We recommend that a meter of type Foo have a builder in the same package named FooBuilder, and this is the practice followed in this project. This MeterBuilder makes up the second parameter to this method, followed by any tags, where a Tag is a simple key/value pair of strings.

==== Example

registry.register(MyInstance.class, new GaugeBuilder(), new Tag("event", "update"), new Tag("source", "mysql"))

[NOTE]
Many metric warehouses are capable of storing and querying multi-dimensional data, and it's the tags used in creating a metric which will become the dimensions of the time series formed by the metric's values. Where a warehouse system is not multi-dimensional, the tags will be used to determine the time series data's hierarchical namespace. In either case, it's best to use tags with consistent ordering and limited cardinality (see <<claxon-tags>> for further advice).

=== Unregister

[small]#`void unregister(Class<?> caller, Tag... tags)`#

You should probably avoid unregistering and re-registering a meter, but if you know that a meter will no longer be used, and should be available for garbage collection, you can call this method.

=== Track _Observable_

[small]#`<O extends Observable> O track(Class<?> caller, MeterBuilder<?> builder, O observable, Tag... tags)`#

Registers a meter that will track changes in an Observable. The Observable instance is only weakly referenced by the meter, so that if the meter is the only remaining reference to the Observable instance, the meter will be unregistered and both the Observable instance and the meter will be available for garbage collection.

=== Track _Lambda_

[small]#`<T> T track(Class<?> caller, MeterBuilder<?> builder, T measured, Function<T, Long> measurement, Tag... tags)`#

Registers a meter that will poll the state of a 'measured' instance on the registry's collection interval using the supplied measurement function. Much like the tracking of Observables above, the measured instance is weakly held, such that if the meter is the only remaining reference, the meter will be unregistered and both the measured instance and the meter will be available for garbage collection.

[[claxon-configuration, Configuration]]
=== Configuration

The configuration for Claxon is simple and, like all SmallMind modules, programmatic. A configuration instance is composed of the following types...

* *Clock* (_clock_) - A clock can provide both wall time (think milliseconds since the epoch) and monotonic time (think nanoseconds). The default clock should work perfectly well, so you should not normally need to set your own.
* *Stint* (_collectionStint_) - The collection interval. The default value represents a 2-second interval.
* *Tag[]* (_registryTags_) - A set of default tags which are to be added to every meter. The default value is empty.
* *NamingStrategy* (_namingStrategy_) - The logic by which the `Class<?> caller` of meter registrations (see <<claxon-registry-register>> above) are turned into the root names of the quantities emitted by those meters (see <<claxon-meters>> below). The default value is the <<claxon-configuration-implied-naming-strategy>>.

[[claxon-naming-strategy, NamingStrategy]]
==== NamingStrategy

The purpose of meters is to emit metrics, or _quantities_ in the parlance of this project (see <<claxon-meters-quantities>> below). Every registered meter has a root name, and every quantity emitted by a meter has a name. The concatenation of the meter's root name with each quantity's name will form the _full_ name of that quantity passed to each of the registry's bound <<claxon-emitters>>. For most types of metric warehouses, the full name of each quantity will form the namespace of the time series created by that quantity's values. Because the emitted quantity namespaces will generally have limited cardinality (for the root names of meters and certainly for the quantity names), it's the Tags submitted with the registration which must guarantee the uniqueness of those namespaces. The root name of a meter is determined by the `Class<?> caller` parameter passed to the `register()` method (see <<claxon-registry-register>> above) via the NamingStrategy (`org.smallmind.claxon.registry.NamingStrategy`) in the registry's configuration. There are two naming strategies included in this project, the *ObviousNamingStrategy* and the *ImpliedNamingStrategy*.

===== ObviousNamingStrategy

[small]#`org.smallmind.claxon.registry.ObviousNamingStrategy``#

The ObviousNamingStrategy holds a Set of <<claxon-dot-notation>> instances which it attempts to match against the names of the caller classes submitted with meter registrations. If any match can be found, then the name of the caller class becomes the root name of the registered meter. If no match can be found, then no meter will be registered, and no metrics will be emitted.

[TIP]
The diversity of this naming should ease the pressure on submitted Tag sets to guarantee the unique namespaces of warehoused time series, however, creators of libraries using this project should not count on this, as it's the choice of the library consumer. It's best to generate Tag sets with enough total cardinality to guarantee unique time series namespaces in their own right.

[[claxon-configuration-implied-naming-strategy, ImpliedNamingStrategy]]
===== ImpliedNamingStrategy

[small]#`org.smallmind.claxon.registry.ImpliedNamingStrategy`#

The ImpliedNamingStrategy holds a Map of _<<claxon-dot-notation>> to String_ entries. This strategy attempts to match the dot notated keys against the names of the caller classes submitted with meter registrations. If no match can be found, then no meter will be registered, and no metrics will be emitted. If one or more matches are found, then the strongest match, which is the one matching the most dot notated segments in the name, will determine the root name for that meter, which will be the String *value* of the winning map entry. Although there's no constraint on the values of this strategy's mappings, it's recommended to use dot notated names. This is the default naming strategy for Claxon configurations.

[TIP]
If you wanted to emit all metrics with a single root name you could add a single _prefixMap_ entry like `put(new DotNotation("*"), "my.metrics")`. Multiple entries can map to the same value, but even if each entry maps to a unique root name, the resulting namespaces are likely to be crowded. It is, therefore, very important that the Tag set registered for each meter guarantee the appropriate differentiation.

[[claxon-dot-notation, DotNotation]]
===== DotNotation

[small]#`org.smallmind.nutsnbolts.util.DotNotation`#

A DotNotation instance represents a pattern match of '.' separated segments, with 2 possible wildcards.

* *?* - Represents any single segment.
* *** - Represents any number of segments.

The greater the number of segments in the matching pattern, the stronger the match is considered, with an exact match counting slightly more than a wildcard match, which will roughly translate to the longest match, by segments, with the fewest wild cards.

===== Examples

The pattern "com.my.names' would match only the exact string, "com.my.names", while the pattern "com.my.?.names.*" would match any dot notated string starting with "com.my." followed by any single segment (a series of characters which was not a '.'), followed by at least one (or any greater number) of dot notated segments.

=== Instrumentation

To make use of this project, you could pass around a registry instance and directly call the `register()` method on it as needed, but that would be less than convenient. Instead, it's easier to interact with the registry through the static methods of the Instrument (`org.smallmind.claxon.registry.Instrument`) class. Instrument uses a thread local context to gain access to the underlying registry, while presenting both a direct access interface that mimics the `register()` and `track()` methods, as well as constructs for wrapping blocks of code with timing-based metrics. Turning on this functionality involves two bits of setup.

. Create an instance of PerApplicationContext (`org.smallmind.nutsnbolts.lang.PerApplicationContext`) which will not be subject to garbage collection for the life of the registry. The easiest way to do this is to create it as a _bean_ within the same IOC (inversion of control) context that you use to configure the Claxon registry instance.
+
[TIP]
====
As old fashioned as this may seem, in Spring xml this would be as simple as...

[source,xml]
----
<bean id="perApplicationContext" class="org.smallmind.nutsnbolts.lang.PerApplicationContext"/>
----
====

. Call the `initializeInstrumentation()` method of the configured ClaxonRegistry instance.
+
[TIP]
The provided `org.smallmind.claxon.registry.spring.ClaxonRegistryFactoryBean` does this for you, if you're using Spring.

==== With

[small]#`Instrumentation with (Class<?> caller, MeterBuilder<?> builder, Tag... tags)`#

The prerequisites taken care of, Instrument functionality is accessed through its `with()` method. This method takes the same _caller_, _builder_ and _tags_ parameters as the `register()` method discussed previously (see <<claxon-registry-register>> above), but returns an instance of the Instrumentation (`org.smallmind.claxon.registry.Instrumentation`) interface. Through this interface you can...

* `track()` to follow either an Obervable object, or any object coupled with a measuring function, as you can with the ClaxonRegistry directly.
+
[NOTE]
====
[source,java]
----
LinkedList<?> myList = new LinkedList();
Instrument.with(MyClass.class, new GaugeBuilder(), new Tag("pool", "used")).track(myList, list -> (long)list.size());
----
====

* `update()` the registered meter with a value, either a simple long value in the default time units (milliseconds), or with an explicit TimeUnit.
+
[NOTE]
====
[source,java]
----
Instrument.with(MyClass.class, new GaugeBuilder(), new Tag("event", "myevent")).update(12345);
----
====

* call `as()` to set the default time unit of the Instrumentation instance.
* call `on()` to wrap a block of code in timing metrics (passed as a Lambda with or without a return value).
+
[NOTE]
====
[source,java]
----
Instrument.with(MyClass.class, new SpeedometerBuilder(), new Tag("event", "myevent"),new Tag("service", "myservice")).on(() -> {
  ...
  instrumented code
  ...
});
----
====

==== Annotations

Although Instrument/Instrumentation together present a fairly simple and fluent interface, Claxon also allows wrapping methods in timing-based metrics via the use of annotations. You can do this not only with the meters which come built in, but also any you might develop.

===== @Instrumented

[small]#`org.smallmind.claxon.registry.aop.Instrumented`#

The root annotation is @Instrumented, which can be applied to both methods and constructors, and takes the following values...

* `Class<?> caller () default Instrumented.class` - The caller which will be passed to the meter registration.
* `ConstantTag[] constants () default {}` - An array of <<claxon-instrumentation-constant-tag>> which defines those tags with constant values that will be passed to the meter registration.
* `ParameterTag[] parameters () default {}` - An array of <<claxon-instrumentation-parameter-tag>> which defines those tags whose values will be pulled from the parameters of the annotated method, and then passed to the meter registration.
* `TimeUnit timeUnit () default TimeUnit.MILLISECONDS` - The time units for the `update()` to the registered meter.
* `boolean active () default true` - Whether this meter is active. If this value is false, no timing update will occur.
* `Class<? extends InstrumentedParser<?>> parser ()` - The class of the <<claxon-instrumentation-instrumented-parser>> which will be used to decode the json string from this annotation (see the json value next), in order to produce a MeterBuilder that will be passed to the meter registration.
* `String json () default "{}"` - The json formatted string representing the meter to be registered via this annotation.

[[claxon-instrumentation-constant-tag, @ConstantTag]]
====== @ConstantTag

Represents a tag whose keys and values are simple string constants.

[[claxon-instrumentation-parameter-tag, @ParameterTag]]
====== @ParameterTag

Represents a tag whose keys are string constants, but whose values are the names of parameters of the annotated method, and whose values will be pulled from those parameters (via their `toString()` methods).

[[claxon-instrumentation-instrumented-parser, InstrumentedParser]]
====== InstrumentedParser

[small]#`org.smallmind.claxon.registry.aop.InstrumentedParser`#

A json parser that accepts a json formatted string and returns an instance of MeterBuilder. Because the parsing of json is a more heavy-weight process that may be repeated many, many times, implementations of this interface will not actually be called unless a new Meter instance is to be constructed, which will only happen if the registry does not already contain an instance matching the caller class and tags. To allow meters you design to be used in @Instrumented annotations, all you need do is create an implementation of this interface and publish its json format and requirements.

====== Example

The following would register a Histogram (`org.smallmind.claxon.registry.meter.Histogram`) and update that meter with the time `myMethod()` takes to execute (in the default time unit of milliseconds). The tags would have the set "const1", "param1" and "param2", where `param1` and `param2` would take their values from the method parameters (_parameter1_ and _parameter2_). The histogram would be built with 2 significant digits of storage, lowest discernible value of 1, highest of 3600000 and tracking percentiles at 75%, 95% and 99%...

[source,java]
----
@Instrumented(
  caller = MyClass.class,
  constants = @ConstantTag(key = "const1", constant = "value"),
  parameters = {@ParameterTag(key = "param1", parameter = "parameter1"), @ParameterTag(key = "param2", parameter = "parameter2")},
  parser = HistogramParser.class,
  json = "{\"numberOfSignificantValueDigits\": 2, \"lowestDiscernibleValue\": 1, \"highestTrackableValue\": 3600000, \"percentiles\": [{\"name\": \"p75\", \"value\": 75.0}, {\"name\": \"p95\", \"value\": 95.0}, {\"name\": \"p99\", \"value\": 99.0}]}"
)
public SomeClass myMethod (String parameter1, int parameter2) {
  ...
  instrumented code
  ...
}
----

[[claxon-meters, Meters]]
== Meters

[small]#`org.smallmind.claxon.registry.meter.Meter`#

A meter in Claxon is an interface with two methods to implement, `update()` and `record()`.

* `void update (long value)` - This method takes a long value and updates the meter. What that means is entirely dependent on the meter, but, generally, the meter will be tracking some series of aggregations over time, to which the updated value will be appended.
* `Quantity[] record ()` - When this method is called by the registry, on the collection interval, the meter should return an array of Quantity instances holding the names and values of its aggregations (or whatever other quantities the meter is designed to track).

Pretty simple. The only complexity is that meters should be multi-thread safe and, as far as possible, lock free and wait free. Multiple threads may be calling the `update()` method at any one time, and, while only one thread *should* be calling `record()`, we don't want updates waiting on each other any more than necessary. Nor should record calls block update operations, and update calls should definitely *not* block record operations. On top of this, a meter must be ready to aggregate its updates in between collection cycles so as not to lose data. And because there's no guarantee of the exact timing of collection cycles, reporting of aggregates that are stated per time unit should internally track the time passed since the last collection, in order to be as accurate as possible.

[TIP]
The Meter implementations in this project use a series of helper classes in the `org.smallmind.claxon.registry.aggregate` package. You may find these helpers useful when designing your own meters as well. You may also want to look at the meter implementations themselves in `org.smallmind.claxon.registry.meter`. Not that the code is any good, but we can always use the help making it better.

[[claxon-meters-quantities, Quantities]]
=== Quantities

[small]#`org.smallmind.claxon.registry.Quantity`#

A quantity is a just container for a String name and a double value. The name of each quantity will be concatenated with the root name provided by the emitting meter to create a namespace for the value that's passed to each warehouse emitter. Exactly how this name is expressed, along with the meter's tags, is up to the logic within each emitter (see <<claxon-emitters>> below). We recommend that quantity names by kept simple. You can distinguish multi-word names via dot notation, hyphens, camel case, or simply smooshing them all together, but be prepared for the emitters to less sophisticated systems to mess with your naming, so simpler is better. We recommend sticking to dot notated names in most cases.

=== Out Of The Box

This project includes a set of Meters in the `org.smallmind.claxon.registry.meter` package.

* *Gauge* - Emits the "minimum", "maximum" and "average" of the updated values over the collection cycle.
* *Histogram* - Emits the "count" of updates, their "velocity", the "minimum", "maximum", "mean", and a set of specified quantiles over the collection cycle.
* *Speedometer* - Emits the "minimum", "maximum" and "velocity" of the updated values over the collection cycle.
* *Tachometer* - Emits just the "velocity" of the updated values over the collection cycle.
* *Tally* - Emits the running total of all updated values (which can be both positive and negative) over the life of the meter.
* *Trace* - Emits the exponential decaying average of the updated values over a set of specified time windows.

[[claxon-tags, Tags]]
== Tags

[small]#`org.smallmind.claxon.registry.Tag`#

A tag is a String name and value. Emitters for warehouses capable of multi-dimensional indexing can usually pass tags directly through to the underlying system. Emitters that represent warehouses that hold time series data, but are not multi-dimensional, will have to use the tags as part of the hierarchical namespace created for each emitted quantity. Other systems will do what they can to create the best experience possible. You can help this process by trying to stick to a few rules...

* Tag names should be kept simple, and, where multi-word names must be used, dot notating is probably best.
* Tag values should have low cardinality where possible. It makes the eventual use of the underlying systems easier. Obviously, a cardinality of 1 is probably too low, and should be either omitted or included in the quantity namespace.
* The Tag set should represent a robust uniqueness, by which we mean that it's unlikely to be duplicated, as a totality, by some other library that happens to be included in the same project. In the end, the client should be able to sort out the proper namespaces given package naming conventions and the available <<claxon-naming-strategy>> implementations. However, each library doing its part will make the whole that much easier to work with.

[[claxon-emitters, Emitters]]
== Emitters

[small]#`org.smallmind.claxon.registry.Emitter`#

There are essentially 2 different ways that metric warehouses ingest data, via either push (such as over a socket, REST API, or by method call) or pull (such as an HTTP scrape endpoint). Although you could implement the Emitter interface directly, we advise extending either the <<claxon-emitters-push-emiiter>> or <<claxon-emitters-pull-emiiter>> abstract classes. In either case, the only requirement is implementing the `record()` method.

* `void record (String meterName, Tag[] tags, Quantity[] quantities)` - The record method is called on each collection cycle once for each registered meter. It's passed the root name of the meter (as determined by the <<claxon-naming-strategy>> in force), an array of the tags registered for that meter, and an array of the quantities being emitted. Whatever an emitter chooses to do with this information should be done efficiently and without blocking. It's up to an emitter to handle any long running operations in an asynchronous fashion, sensitive to the fact that record might be called again before the current asynchronous operation is complete.

[[claxon-emitters-push-emiiter, PushEmitter]]
=== PushEmitter

A PushEmitter can generally take the information in the record call and translate it to the underlying warehouse system, assuming such calls are efficient in their own right.

[small]#`org.smallmind.claxon.registry.PushEmitter`#

[[claxon-emitters-pull-emiiter, PullEmitter]]
=== PullEmitter

[small]#`org.smallmind.claxon.registry.PullEmitter`#

A PullEmitter will have to store and forward incoming time series data by necessity. Given that Claxon expects meters to aggregate updates between collection intervals, pull-based emitters may be receiving multiple sets of aggregates before being able to pass that data on to the underlying warehouse, depending on the timing of Claxon collection cycles and those of the underlying system. As the methods of aggregation, if any, will vary from meter to meter, a pull-based emitter can't simply squash aggregates together, and should be prepared to send them on as independent values, along with their original timestamps.

==== EmitterResource

[small]#`org.smallmind.claxon.http.EmitterResource`#

Claxon provides a generic Jersey REST API endpoint for pull-based emitters, such as Prometheus, available in the *claxon-http* artifact (see <<claxon-maven-pull-based>> above). If the provided implementation is not appropriate for your project, building your own should be simple enough considering the few lines of code it took to implement ours.

=== Out Of The Box

Claxon provides emitters for the following systems as part of this project...

==== DataDog

This is fairly straightforward. The integration uses DataDog's StatsD capabilities, which, being UDP-based, is very fast, and cares little about the choice of characters in its namespace or tags. It's push capable, allowing aggregations to be forwarded as necessary. DataDog prefers dot notated names, in keeping with the general precedent set by almost every programming language, which lowers the impedance mismatch which might otherwise occur. All quantities are output as gauge values, as all aggregation is assumed to be handled client side. All of this should lead to an experience with few surprises.

==== JMX

JMX knows nothing about time series, so the resulting management beans will contain only the last known data points. The translation is otherwise pretty direct, with dot notated meter names making up the JMX domain name, tags creating the attendant properties, and quantity names translating to available fields.

==== Message

A very simple translation to string values handed off to a `Consumer<String>`, intended for easy integration with logging systems.

==== Prometheus

Beware when using Prometheus that its scrape protocol is limited. You might think it would be easy enough to allow multiple data points for any single time series, within the same scrape Http body, by referencing the timestamp value the protocol allows to be included with each data point, and, where that was either not present or not sufficient, relying on the simple ordering of the values themselves. However, that is not the case and multiple data points for the same series will be lost. Due to this limitation, Claxon's Prometheus integration will only report the last data point received for any series since the last scrape request. It's important, therefore, to have your Prometheus instance scrape the Claxon endpoint at least as often as Claxon is set to report its aggregated values. In practical terms...

[WARNING]
The Prometheus collection interval must be less than or equal to the Claxon collection interval as defined by `ClaxonConfiguration.getCollectionStint()`, _or you may lose data points_.

===== Naming

Prometheus does not allow dot notated names, nor anything but the most basic ascii characters and numbers. The more natural dot notated names used by Claxon will be translated to underscore separated names. Most everything otherwise inadmissible for prometheus will also end up as underscores. Fortunately, prometheus is muti-dimensional and Claxon's guidelines for tags are in line with those promulgated by Prometheus.

[[scribe,Scribe]]
= Scribe

[partintro]
Scribe is a logging framework with no specific dependency on a logger endpoint. It can be safely used in libraries without forcing any particular notion of the endpoint logging system on the library adopter. It is programmatically configurable and has no proprietary configuration format. Scribe can consume and integrate both Apache Commons Logging and SLF4J logging. Scribe's adapters for endpoint logging systems are written as services, so, when choosing a logging endpoint in top-level projects, it's enough to include the desired module as a project dependency. Scribe has a notion of thread local context which flows through to the context implementations of endpoint logger adapters. Scribe is fast, efficient, and easy to extend. The implementation requirements for adapters, appenders, filters and formatters are clear and minimal.

== Install

To use Scribe you'll need the `scribe-pen` dependency, and, if using an endpoint logger, you'll need to add the appropriate `scribe-ink-*` module. Integration with Apache Commons Logging is achieved through adding the `scribe-apache` module, and with SLF4J by adding the `scribe-slf4j` module.

.Scribe Pen
[source,xml]
----
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>scribe-pen</artifactId>
  <version>LATEST</version>
</dependency>
----

.Scribe Ink
[source,xml]
----
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>scribe-ink-indigenous</artifactId>
  <version>LATEST</version>
</dependency>
----

.Scribe Integrations
[source,xml]
----
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>scribe-apache</artifactId>
  <version>LATEST</version>
</dependency>
<dependency>
  <groupId>org.smallmind</groupId>
  <artifactId>scribe-slf4j</artifactId>
  <version>LATEST</version>
</dependency>
----

== Acknowledgments

Thanks to SLF4J.

== Design Choices

There are a few simple reasons for designing yet another logging framework almost no one will ever use...

* Programmatic configuration at its heart. Nothing but dependency injection.
* Simple implementation of extensions with no priveleged internals and minimal biases.
* No logging level checks necessary because expensive operations are delayed until the output stage.
* Where an expensive operation is necessary, it can be defined in a way which allows its execution to be delayed until the output stage.
* Native message formatting using the _printf_ style from `String.format()`.
* The last argument in *all* logging methods is the _var args_ for message formatting, and this includes those methods which take an Exception (so you can add an exception without losing formatted messages).

And that last reason is honestly the one which started this project. Hopefully it's not the only one for using it, but, for us, it's enough.

[[scribe-logger, Logger]]
== Logger

[small]#`org.smallmind.scribe.pen.Logger`#

The mechanism of logging in Scribe is a Logger. A logger has a <<scribe-logger-name>> and a <<scribe-level>> at which it will log, may have a <<scribe-logical-context>>, holds <<scribe-appenders>>, <<scribe-filters>> and <<scribe-enhancer>>, and can decorate logs with <<scribe-parameters>>. The basic function of a Logger is expressed through its `log()` methods....

* `void log (Level level, String message, Object... args)`
* `void log (Level level, Throwable throwable)`
* `void log (Level level, Throwable throwable, String message, Object... args)`
* `void log (Level level, Object object)`
* `void log (Level level, Throwable throwable, Object object)`
* `void log (Level level, Supplier<String> supplier)`
* `void log (Level level, Throwable throwable, Supplier<String> supplier)`

Each log statement has a _<<scribe-level>>_ at which it will be logged, can take a _Throwable_ to provide the stack trace output of an error, and takes one of three forms of message body...

* *Formatted* - Formatted messages take a base _String_ message and an optional set of arguments. If any arguments are passed, the message will be interpreted as a formatting template via the `String.format()` method, with the arguments passed as the formatting arguments.
* *Object* - If a single _Object_ is provided as the log message, the output will be the result of the object's `toString()` method. As message interpolation is delayed until after all filtering, this is one way of guaranteeing that complex or expensive operations to generate a log message will not be performed unless they are needed.
* *Supplier* - If a single _Supplier<String>_ is provided as the log message, the ouput will be the result of the supplier's `get()` method. As with using a simple _Object_ above, this can be used to delay complex or expensive operations until they are required.

For the sake of clarity and convenience, the above methods are replicated, once for each available log <<scribe-level>> (sans the _Level_ parameter, obviously), as in...

.An Info level log with a formatted messge
[source,java]
----
void info (String message, Object... args)
----

...or...

.A Warn level log with a _Throwable_ and _Supplier_
[source,java]
----
void warn (Throwable throwable, Supplier<String> supplier)
----

[[scribe-logger-name, Name]]
=== Name

Every logger instance has a name by which it's retrieved (see <<scribe-logger-manager>> below), by which its configuration may be fine-tuned (see <<scribe-configuration>> below), and by which it may be known in log output. Although the choice of name is yours, it's suggested that you stick with the name of the class doing the logging.

[[scribe-level, Level]]
=== Level

[small]#`org.smallmind.scribe.pen.Level`#

The available log levels, which provide for basic categorization and filtering of log entries, are represented by the *Level* enum, which contains the following ordinal values...

* *TRACE* - Intended for very fine gained more-than-debug logging.
* *DEBUG* - For traditional debug logs.
* *INFO* - Informational messages, for example service startups and shutdowns, initial conditions, etc.
* *WARN* - Intended for possible problems or misconfigurations which do not rise to the level of overt errors.
* *ERROR* - A notice that something has gone wrong, often including an exception.
* *FATAL* - Intended for world-stopping events which cause shutdown or other unrecoverable states.
* *OFF* - Do not log. For use on <<scribe-logger>> instances or <<scribe-appenders>>, in order to shut them off. This should *never* be used as the level of a `log()` event.

[[scribe-logical-context, Logical Context]]
=== Logical Context

[[scribe-appenders, Appenders]]
=== Appenders

==== More Filters

==== Formatted Appender

===== Formatter

==== Out Of The Box

[[scribe-filters, Filters]]
=== Filters

[[scribe-enhancer, Enhancers]]
=== Enhancers

[[scribe-parameters, Parameters]]
=== Parameters

== Adaptation

=== Blueprint

=== LoggerAdapter

=== Record

=== Parameter Adapter

[[scribe-configuration, Configuration]]
== Configuration

[[scribe-logger-manager, LoggerManager]]
== LoggerManager

[small]#`org.smallmind.scribe.pen.LoggerManager`#

== Apache Commons Logging Integration

== SLF4J Integration

[[spark,Spark]]
= Spark

[partintro]
The Spark project consists of Maven packaging formats for the construction of self-contained executable build artifacts.

[[spark-singularity,Singularity]]
== Singularity

Singularity is a Maven packaging format for executable jars *with* all their dependencies. Notably, a Singularity package does not unpack and repack its dependencies. The original jar files are maintained, and their namespaces are preserved. In order to speed class resolution and loading, indexes are built on compilation through a bit of Maven plugin magic. There should be nothing special you need to do with your code to create a Singulairty from it, other than defining the packaging and nominating a `public static void main (String... args)` entry point.

=== Install

In order to have Maven create a self-contained jar you should declare the packaging as `singularity` and include the `spark-singularity-maven-plugin` as outlined below..

.Singularity Plugin
[source,xml]
----
<project>
  ...
  <packaging>singularity</packaging>
  ...
  <build>
    <plugins>
      <plugin>
        <groupId>org.smallmind</groupId>
        <artifactId>spark-singularity-maven-plugin</artifactId>
        <version>LATEST</version>
        <extensions>true</extensions>
        <configuration>
          <mainClass><!-- entry point class containing a main() method --></mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
----

=== Configuration

The following configuration attributes are supported by the plugin...

* *mainClass* (required) - An entry point class containing a standard `public static void main (String... args)` method.
+
.Example
[source,xml]
----
<mainClass>my.Main</mainClass>
----

* *skip* (optional, defaults to _false_) - If this attribute exists and is set `true`, then the plugin will skip its operations and no artifact will be produced.
+
.Example
[source,xml]
----
<skip>true</skip>
----