/*
 * Copyright (c) 2007 through 2026 David Berkman
 *
 * This file is part of the SmallMind Code Project.
 *
 * The SmallMind Code Project is free software, you can redistribute
 * it and/or modify it under either, at your discretion...
 *
 * 1) The terms of GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * ...or...
 *
 * 2) The terms of the Apache License, Version 2.0.
 *
 * The SmallMind Code Project is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License or Apache License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * and the Apache License along with the SmallMind Code Project. If not, see
 * <http://www.gnu.org/licenses/> or <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Additional permission under the GNU Affero GPL version 3 section 7
 * ------------------------------------------------------------------
 * If you modify this Program, or any covered work, by linking or
 * combining it with other code, such other code is not for that reason
 * alone subject to any of the requirements of the GNU Affero GPL
 * version 3.
 */
package org.smallmind.file.ephemeral.watch;

import java.nio.file.WatchEvent;

/**
 * Immutable {@link WatchEvent} implementation used by the ephemeral watch subsystem.
 *
 * <p>Instances are created by {@link EphemeralWatchKey#fire(WatchEvent.Kind)} and placed on
 * the key's internal queue. Each event captures the {@link WatchEvent.Kind kind} of change
 * that occurred, the number of times the event was coalesced into this single record, and an
 * optional context value (typically the relative path of the affected entry).
 *
 * @param <T> the type of the context object associated with this event (commonly
 *            {@link java.nio.file.Path})
 */
public class EphemeralWatchEvent<T> implements WatchEvent<T> {

  /**
   * The kind of file-system change that this event represents.
   */
  private final Kind<T> kind;

  /**
   * The context for the event, such as the path of the file that was created, modified,
   * or deleted, relative to the watched directory. May be {@code null}.
   */
  private final T context;

  /**
   * The number of times the underlying change was observed and coalesced into this single
   * event record.
   */
  private final int count;

  /**
   * Creates a new watch event with the supplied kind, coalesced count, and context.
   *
   * @param kind    the {@link WatchEvent.Kind} describing the type of change; must not be
   *                {@code null}
   * @param count   the number of times the event has been coalesced; typically {@code 1}
   *                for events generated by the ephemeral file system
   * @param context the context associated with the event (e.g. the relative path of the
   *                affected file), or {@code null} if no context applies
   */
  public EphemeralWatchEvent (Kind<T> kind, int count, T context) {

    this.kind = kind;
    this.count = count;
    this.context = context;
  }

  /**
   * Returns the kind of event that occurred, such as
   * {@link java.nio.file.StandardWatchEventKinds#ENTRY_CREATE},
   * {@link java.nio.file.StandardWatchEventKinds#ENTRY_DELETE}, or
   * {@link java.nio.file.StandardWatchEventKinds#ENTRY_MODIFY}.
   *
   * @return the {@link WatchEvent.Kind} of this event; never {@code null}
   */
  @Override
  public Kind<T> kind () {

    return kind;
  }

  /**
   * Returns the number of times the underlying file-system change was observed and folded
   * into this single event record. Events generated by the ephemeral file system always
   * have a count of {@code 1}.
   *
   * @return the coalesced occurrence count; always positive
   */
  @Override
  public int count () {

    return count;
  }

  /**
   * Returns the context associated with this event. For events whose kind is a
   * {@link java.nio.file.StandardWatchEventKinds} entry event, the context is typically
   * the relative path of the affected file within the watched directory. For overflow
   * events the context may be {@code null}.
   *
   * @return the event context, or {@code null} if none was provided at construction time
   */
  @Override
  public T context () {

    return context;
  }
}
