/*
 * Copyright (c) 2007 through 2026 David Berkman
 *
 * This file is part of the SmallMind Code Project.
 *
 * The SmallMind Code Project is free software, you can redistribute
 * it and/or modify it under either, at your discretion...
 *
 * 1) The terms of GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * ...or...
 *
 * 2) The terms of the Apache License, Version 2.0.
 *
 * The SmallMind Code Project is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License or Apache License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * and the Apache License along with the SmallMind Code Project. If not, see
 * <http://www.gnu.org/licenses/> or <http://www.apache.org/licenses/LICENSE-2.0>.
 *
 * Additional permission under the GNU Affero GPL version 3 section 7
 * ------------------------------------------------------------------
 * If you modify this Program, or any covered work, by linking or
 * combining it with other code, such other code is not for that reason
 * alone subject to any of the requirements of the GNU Affero GPL
 * version 3.
 */
package org.smallmind.claxon.registry;

import java.util.Arrays;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Function;
import org.smallmind.claxon.registry.feature.Feature;
import org.smallmind.claxon.registry.meter.Meter;
import org.smallmind.claxon.registry.meter.MeterBuilder;
import org.smallmind.scribe.pen.LoggerManager;

/**
 * Central registry that holds meters, periodically collects their readings, and dispatches them to configured emitters.
 */
public class ClaxonRegistry {

  private final ConcurrentHashMap<String, Emitter> emitterMap = new ConcurrentHashMap<>();
  private final ConcurrentHashMap<RegistryKey, NamedMeter<? extends Meter>> meterMap = new ConcurrentHashMap<>();
  private final Set<RegistryKey> noopSet = ConcurrentHashMap.newKeySet();
  private final MeasurableTracker measurableTracker;
  private final CollectionWorker collectionWorker;
  private final ClaxonConfiguration configuration;

  /**
   * Creates a registry configured with the supplied settings and starts the background collection worker.
   *
   * @param configuration registry configuration options
   */
  public ClaxonRegistry (ClaxonConfiguration configuration) {

    Thread workerThread = new Thread(collectionWorker = new CollectionWorker());

    this.configuration = configuration;

    measurableTracker = new MeasurableTracker(this);

    workerThread.setDaemon(true);
    workerThread.start();
  }

  public void initializeInstrumentation () {

    Instrument.register(this);
  }

  /**
   * @return the configuration used by this registry
   */
  public ClaxonConfiguration getConfiguration () {

    return configuration;
  }

  /**
   * Stops the background collection worker and waits for it to finish.
   *
   * @throws InterruptedException if interrupted while waiting
   */
  public void stop ()
    throws InterruptedException {

    collectionWorker.stop();
  }

  /**
   * Looks up an emitter by name.
   *
   * @param name emitter name
   * @return the emitter instance or {@code null} if not bound
   */
  public Emitter getEmitter (String name) {

    return emitterMap.get(name);
  }

  /**
   * Binds a named emitter to the registry for future emission.
   *
   * @param name    logical emitter name
   * @param emitter emitter instance
   * @return this registry for chaining
   */
  public ClaxonRegistry bind (String name, Emitter emitter) {

    emitterMap.put(name, emitter);

    return this;
  }

  /**
   * Registers or retrieves a meter for the given caller, builder, and tags.
   * Falls back to {@link NoOpMeter} when no name can be generated by the configured strategy.
   *
   * @param caller  class requesting the meter
   * @param builder builder used to create the meter
   * @param tags    tags describing the meter
   * @return the active meter or a no-op meter when registration fails
   */
  public Meter register (Class<?> caller, MeterBuilder<? extends Meter> builder, Tag... tags) {

    RegistryKey key = new RegistryKey(caller, tags);

    if (noopSet.contains(key)) {

      return NoOpMeter.instance();
    } else {

      NamedMeter<? extends Meter> namedMeter;

      if ((namedMeter = meterMap.get(key)) == null) {

        String meterName;

        if ((meterName = configuration.getNamingStrategy().from(caller)) == null) {
          noopSet.add(key);

          return NoOpMeter.instance();
        } else {

          NamedMeter<? extends Meter> previousNamedMeter;

          if ((previousNamedMeter = meterMap.putIfAbsent(key, namedMeter = new NamedMeter<>(meterName, builder))) != null) {

            return previousNamedMeter.getMeter();
          } else {

            return namedMeter.getMeter();
          }
        }
      } else {

        return namedMeter.getMeter();
      }
    }
  }

  public void unregister (Class<?> caller, Tag... tags) {

    meterMap.remove(new RegistryKey(caller, tags));
  }

  /**
   * Begins tracking a measured object, automatically updating and unregistering its meter as the object is collected.
   *
   * @param caller      class requesting the meter
   * @param builder     builder used to create the meter
   * @param measured    object being tracked
   * @param measurement measurement function
   * @param tags        tags describing the meter
   * @param <T>         measured type
   * @return the measured object
   */
  public <T> T track (Class<?> caller, MeterBuilder<? extends Meter> builder, T measured, Function<T, Long> measurement, Tag... tags) {

    return measurableTracker.track(caller, builder, measured, measurement, tags);
  }

  private class CollectionWorker implements Runnable {

    private final CountDownLatch finishLatch = new CountDownLatch(1);
    private final CountDownLatch exitLatch = new CountDownLatch(1);

    /**
     * Signals the worker to stop and waits for completion.
     *
     * @throws InterruptedException if interrupted while waiting
     */
    public void stop ()
      throws InterruptedException {

      finishLatch.countDown();
      exitLatch.await();
    }

    /**
     * Periodically collects feature and meter readings and forwards them to each emitter.
     * Any exceptions from emitters are logged but do not stop the collection loop.
     */
    @Override
    public void run () {

      try {
        while (!finishLatch.await(configuration.getCollectionStint().getTime(), configuration.getCollectionStint().getTimeUnit())) {

          Feature[] features;

          measurableTracker.sweepAndUpdate();

          if ((features = configuration.getFeatures()) != null) {
            for (Feature feature : features) {

              Quantity[] quantities = feature.record();

              if ((quantities != null) && (quantities.length > 0)) {
                for (Emitter emitter : emitterMap.values()) {
                  try {
                    emitter.record(feature.getName(), configuration.calculateTags(feature.getName(), feature.getTags()), quantities);
                  } catch (Exception exception) {
                    LoggerManager.getLogger(ClaxonRegistry.class).error(exception);
                  }
                }
              }
            }
          }

          for (Map.Entry<RegistryKey, NamedMeter<? extends Meter>> namedMeterEntry : meterMap.entrySet()) {

            Quantity[] quantities = namedMeterEntry.getValue().getMeter().record();

            if ((quantities != null) && (quantities.length > 0)) {
              for (Emitter emitter : emitterMap.values()) {
                try {
                  emitter.record(namedMeterEntry.getValue().getName(), configuration.calculateTags(namedMeterEntry.getValue().getName(), namedMeterEntry.getKey().tags()), quantities);
                } catch (Exception exception) {
                  LoggerManager.getLogger(ClaxonRegistry.class).error(exception);
                }
              }
            }
          }
        }
      } catch (InterruptedException interruptedException) {
        LoggerManager.getLogger(ClaxonRegistry.class).error(interruptedException);
        finishLatch.countDown();
      } finally {
        exitLatch.countDown();
      }
    }
  }

  private class NamedMeter<M extends Meter> {

    private final String name;
    private final MeterBuilder<M> builder;
    private final AtomicReference<M> meterRef = new AtomicReference<>();

    /**
     * Wraps a meter builder with its derived name and caches the built meter.
     *
     * @param name    derived meter name
     * @param builder builder used to construct the meter
     */
    public NamedMeter (String name, MeterBuilder<M> builder) {

      this.name = name;
      this.builder = builder;
    }

    /**
     * @return the derived meter name
     */
    public String getName () {

      return name;
    }

    /**
     * Lazily builds and returns the meter instance.
     *
     * @return meter instance
     */
    public M getMeter () {

      M meter;

      if ((meter = meterRef.get()) == null) {
        synchronized (meterRef) {
          if ((meter = meterRef.get()) == null) {
            meterRef.set(meter = builder.build(configuration.getClock()));
          }
        }
      }

      return meter;
    }
  }

  private record RegistryKey(Class<?> caller, Tag... tags) {

    /**
     * Computes a hash based on caller and tags.
     *
     * @return hash code
     */
    @Override
    public int hashCode () {

      return (caller.hashCode() * 31) + ((tags == null) ? 0 : Arrays.hashCode(tags));
    }

    /**
     * Compares registry keys by caller and tags.
     *
     * @param obj object to compare
     * @return {@code true} when caller and tags match
     */
    @Override
    public boolean equals (Object obj) {

      return (obj instanceof RegistryKey) && ((RegistryKey)obj).caller().equals(caller) && Arrays.equals(((RegistryKey)obj).tags(), tags);
    }
  }
}
